
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-04
owner: ucsb-cs156-s25
repo_name: team01-s25-04
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ5ODgzNjQy","is_bot":false,"login":"jeremiahwong704","name":"Jeremiah Wong"},"headRefName":"jeremiah-menuitemreview","number":49,"title":"added PUT for ucsbmenuitemreview","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/49"},{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-RecommendationRequestTable","number":46,"title":"Create RecommendationRequest for db","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/46"},{"author":{"id":"U_kgDOCMR7LA","is_bot":false,"login":"Asuasuasu1","name":"Montgomery Forde"},"headRefName":"Montgomery-UCSBOrganization-create-db","number":45,"title":"mf - create database table for UCSBOrganizations","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/45"}]
