
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-04
owner: ucsb-cs156-s25
repo_name: team01-s25-04
pull_requests: [{"author":{"id":"U_kgDOCt_6qQ","is_bot":false,"login":"Renbo2004","name":""},"headRefName":"Renbo-articles-put","number":62,"title":"Renbo-articles-add-put","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/62"},{"author":{"id":"U_kgDOCt_6qQ","is_bot":false,"login":"Renbo2004","name":""},"headRefName":"Renbo-articles-get-by-id","number":61,"title":"Renbo-add-articles-get-by-id","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/61"},{"author":{"id":"U_kgDOCvDiEw","is_bot":false,"login":"ZFahim10","name":""},"headRefName":"Fahim-HelpRequestController","number":60,"title":"fz - Controller for HelpRequest along side test coverage and slight t…","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/60"},{"author":{"id":"U_kgDOCt_6qQ","is_bot":false,"login":"Renbo2004","name":""},"headRefName":"Renbo-ArticlesController","number":59,"title":"pc - create-articles-controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/59"},{"author":{"id":"U_kgDOCt_6qQ","is_bot":false,"login":"Renbo2004","name":""},"headRefName":"Renbo-Articles-create-db","number":57,"title":"pc -Create database table for Articles","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/57"}]
