
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-04
owner: ucsb-cs156-s25
repo_name: team01-s25-04
pull_requests: [{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-RecommendationRequestControllerGetId","number":72,"title":"Add RecommendationController get by Id","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/72"},{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-RecommendationRequestController","number":71,"title":"Add RecommendationRequestController and tests","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/71"},{"author":{"id":"U_kgDOCMR7LA","is_bot":false,"login":"Asuasuasu1","name":"Montgomery Forde"},"headRefName":"Montgomery-UCSBOrganization-put","number":70,"title":"Montgomery ucsb organization put","url":"https://github.com/ucsb-cs156-s25/team01-s25-04/pull/70"}]
